/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type BusinessMemberRole = "manager" | "owner" | "staff";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MembershipStatus = "active" | "invited" | "suspended";

export type Numeric = ColumnType<string, number | string, number | string>;

export type PaymentMethod = "bank" | "card" | "cash" | "other" | "upi";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TransactionStatus = "cancelled" | "confirmed" | "draft";

export type UserRole = "admin" | "user";

export interface AuditLog {
  action: string;
  businessId: string | null;
  createdAt: Generated<Timestamp>;
  entityId: string | null;
  entityType: string;
  id: Generated<string>;
  metadata: Json | null;
  userId: Int8 | null;
}

export interface Businesses {
  address: string | null;
  businessType: Generated<string>;
  city: string | null;
  countryCode: Generated<string>;
  createdAt: Generated<Timestamp>;
  currencyCode: Generated<string>;
  id: Generated<string>;
  logoUrl: string | null;
  mobile: string | null;
  name: string;
  ownerName: string | null;
  pinCode: string | null;
  preferredLanguage: Generated<string>;
  state: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface BusinessMemberships {
  businessId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  role: Generated<BusinessMemberRole>;
  status: Generated<MembershipStatus>;
  updatedAt: Generated<Timestamp>;
  userId: Int8;
}

export interface BusinessSettings {
  businessId: string;
  dateFormat: Generated<string>;
  defaultPaymentMethod: Generated<PaymentMethod>;
  lowStockThreshold: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
}

export interface CollectionPayments {
  amountApplied: Numeric;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  paymentId: string;
  scheduleId: string;
}

export interface CollectionSchedules {
  businessId: string;
  createdAt: Generated<Timestamp>;
  customerId: string;
  frequency: Generated<string>;
  id: Generated<string>;
  installmentAmount: Numeric;
  isActive: Generated<boolean>;
  nextDueDate: Timestamp | null;
  notes: string | null;
  outstandingAmount: Generated<Numeric>;
  saleId: string | null;
  startDate: Generated<Timestamp>;
  title: string;
  totalAmount: Numeric;
  updatedAt: Generated<Timestamp>;
}

export interface Customers {
  address: string | null;
  alternateMobile: string | null;
  businessId: string;
  createdAt: Generated<Timestamp>;
  creditLimit: Generated<Numeric>;
  id: Generated<string>;
  isActive: Generated<boolean>;
  mobile: string | null;
  name: string;
  notes: string | null;
  openingBalance: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
}

export interface Expenses {
  amount: Numeric;
  businessId: string;
  category: string;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  expenseDate: Generated<Timestamp>;
  id: Generated<string>;
  notes: string | null;
  paymentMethod: Generated<PaymentMethod>;
}

export interface InventoryMovements {
  businessId: string;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  id: Generated<string>;
  locationId: string;
  movementType: string;
  notes: string | null;
  productId: string;
  quantity: Numeric;
  referenceId: string | null;
  referenceType: string | null;
  unitCost: Generated<Numeric>;
}

export interface Locations {
  address: string | null;
  businessId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isActive: Generated<boolean>;
  locationType: Generated<string>;
  name: string;
  responsibleUserId: Int8 | null;
  updatedAt: Generated<Timestamp>;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface Payments {
  amount: Numeric;
  businessId: string;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  customerId: string | null;
  id: Generated<string>;
  notes: string | null;
  paymentDate: Generated<Timestamp>;
  paymentMethod: PaymentMethod;
  purchaseId: string | null;
  reference: string | null;
  saleId: string | null;
  supplierId: string | null;
}

export interface Products {
  businessId: string;
  category: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isActive: Generated<boolean>;
  name: string;
  notes: string | null;
  photoUrl: string | null;
  purchasePrice: Generated<Numeric>;
  reorderLevel: Generated<Numeric>;
  salePrice: Generated<Numeric>;
  sku: string | null;
  unit: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface PurchaseLines {
  id: Generated<string>;
  lineTotal: Generated<Numeric>;
  productId: string;
  purchaseId: string;
  quantity: Numeric;
  unitPrice: Generated<Numeric>;
}

export interface Purchases {
  businessId: string;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  discount: Generated<Numeric>;
  id: Generated<string>;
  locationId: string | null;
  notes: string | null;
  paidAmount: Generated<Numeric>;
  paymentMethod: PaymentMethod | null;
  purchaseDate: Generated<Timestamp>;
  purchaseNumber: string;
  status: Generated<TransactionStatus>;
  subtotal: Generated<Numeric>;
  supplierId: string | null;
  totalAmount: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
}

export interface SaleLines {
  id: Generated<string>;
  lineTotal: Generated<Numeric>;
  productId: string;
  quantity: Numeric;
  saleId: string;
  unitPrice: Generated<Numeric>;
}

export interface Sales {
  balanceAmount: Generated<Numeric>;
  businessId: string;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  customerId: string | null;
  discount: Generated<Numeric>;
  id: Generated<string>;
  locationId: string | null;
  notes: string | null;
  paidAmount: Generated<Numeric>;
  paymentMethod: PaymentMethod | null;
  saleDate: Generated<Timestamp>;
  saleNumber: string;
  status: Generated<TransactionStatus>;
  subtotal: Generated<Numeric>;
  totalAmount: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface Suppliers {
  address: string | null;
  businessId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isActive: Generated<boolean>;
  mobile: string | null;
  name: string;
  notes: string | null;
  openingBalance: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  auditLog: AuditLog;
  businesses: Businesses;
  businessMemberships: BusinessMemberships;
  businessSettings: BusinessSettings;
  collectionPayments: CollectionPayments;
  collectionSchedules: CollectionSchedules;
  customers: Customers;
  expenses: Expenses;
  inventoryMovements: InventoryMovements;
  locations: Locations;
  loginAttempts: LoginAttempts;
  payments: Payments;
  products: Products;
  purchaseLines: PurchaseLines;
  purchases: Purchases;
  saleLines: SaleLines;
  sales: Sales;
  sessions: Sessions;
  suppliers: Suppliers;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const BusinessMemberRoleArrayValues: [BusinessMemberRole, ...BusinessMemberRole[]] = ["manager","owner","staff"];
export const MembershipStatusArrayValues: [MembershipStatus, ...MembershipStatus[]] = ["active","invited","suspended"];
export const PaymentMethodArrayValues: [PaymentMethod, ...PaymentMethod[]] = ["bank","card","cash","other","upi"];
export const TransactionStatusArrayValues: [TransactionStatus, ...TransactionStatus[]] = ["cancelled","confirmed","draft"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.