import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useSearchParams, useNavigate } from "react-router-dom";
import { Boxes, PackagePlus, Plus, Users } from "lucide-react";
import { Button } from "../components/Button";
import { Input } from "../components/Input";
import { Form, FormControl, FormItem, FormLabel, FormMessage, useForm } from "../components/Form";
import { Spinner } from "../components/Spinner";
import { useBusinesses } from "../helpers/useBusinesses";
import { getProducts } from "../endpoints/products_GET.schema";
import { postProduct, schema as productSchema } from "../endpoints/products_POST.schema";
import { getCustomers } from "../endpoints/customers_GET.schema";
import { postCustomer, schema as customerSchema } from "../endpoints/customers_POST.schema";
import styles from "./operations.module.css";

export default function OperationsPage(){
 const navigate=useNavigate();const [params]=useSearchParams();const focus=params.get("focus")||"products";const {selectedBusinessId,selectedBusiness}=useBusinesses();const businessId=selectedBusinessId||params.get("businessId");const qc=useQueryClient();
 const products=useQuery({queryKey:["products",businessId],queryFn:()=>getProducts(businessId!),enabled:!!businessId});const customers=useQuery({queryKey:["customers",businessId],queryFn:()=>getCustomers(businessId!),enabled:!!businessId});
 const [tab,setTab]=useState(focus==="customers"?"customers":"products");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
 const pf=useForm({schema:productSchema,defaultValues:{businessId:businessId||"",name:"",sku:"",category:"",unit:"pcs",salePrice:0,purchasePrice:0,reorderLevel:0}});const cf=useForm({schema:customerSchema,defaultValues:{businessId:businessId||"",name:"",mobile:"",address:"",openingBalance:0}});
 useEffect(()=>{if(businessId){pf.setValues(v=>({...v,businessId}));cf.setValues(v=>({...v,businessId}))}},[businessId]);
 const createProduct=async(v:typeof pf.values)=>{setBusy(true);setError(null);try{await postProduct(v);pf.setValues(x=>({...x,name:"",sku:"",category:"",unit:"pcs",salePrice:0,purchasePrice:0,reorderLevel:0}));await qc.invalidateQueries({queryKey:["products",businessId]})}catch(e){setError(e instanceof Error?e.message:"Unable to save product")}finally{setBusy(false)}};
 const createCustomer=async(v:typeof cf.values)=>{setBusy(true);setError(null);try{await postCustomer(v);cf.setValues(x=>({...x,name:"",mobile:"",address:"",openingBalance:0}));await qc.invalidateQueries({queryKey:["customers",businessId]})}catch(e){setError(e instanceof Error?e.message:"Unable to save customer")}finally{setBusy(false)}};
 if(!businessId)return <main className={styles.empty}><h1>Set up your business first</h1><Button onClick={()=>navigate("/onboarding")}>Business setup</Button></main>;
 return <main className={styles.page}><header className={styles.header}><div><p className={styles.kicker}>OPERATIONS</p><h1>{selectedBusiness?.name||"Your business"}</h1><p>Build your real catalog and customer records. Every record belongs to this business.</p></div><Button variant="outline" onClick={()=>navigate("/")}>Dashboard</Button></header>
 <div className={styles.tabs}><Button variant={tab==="products"?"primary":"outline"} onClick={()=>setTab("products")}><Boxes size={17}/> Products</Button><Button variant={tab==="customers"?"primary":"outline"} onClick={()=>setTab("customers")}><Users size={17}/> Customers</Button></div>
 {error&&<div className={styles.error}>{error}</div>}
 {tab==="products"?<section className={styles.grid}><article className={styles.formCard}><div className={styles.cardHead}><PackagePlus size={20}/><div><h2>Add product</h2><p>Use simple fields now; richer industry fields can be added later.</p></div></div><Form {...pf}><form onSubmit={pf.handleSubmit(createProduct)} className={styles.form}><FormItem name="name"><FormLabel>Product name</FormLabel><FormControl><Input placeholder="e.g. Item name" value={pf.values.name} onChange={e=>pf.setValues(v=>({...v,name:e.target.value}))}/></FormControl><FormMessage/></FormItem><div className={styles.two}><FormItem name="sku"><FormLabel>SKU (optional)</FormLabel><FormControl><Input value={pf.values.sku} onChange={e=>pf.setValues(v=>({...v,sku:e.target.value}))}/></FormControl></FormItem><FormItem name="category"><FormLabel>Category</FormLabel><FormControl><Input value={pf.values.category} onChange={e=>pf.setValues(v=>({...v,category:e.target.value}))}/></FormControl></FormItem></div><div className={styles.two}><FormItem name="purchasePrice"><FormLabel>Purchase price</FormLabel><FormControl><Input inputMode="decimal" type="number" value={pf.values.purchasePrice} onChange={e=>pf.setValues(v=>({...v,purchasePrice:Number(e.target.value)}))}/></FormControl></FormItem><FormItem name="salePrice"><FormLabel>Sale price</FormLabel><FormControl><Input inputMode="decimal" type="number" value={pf.values.salePrice} onChange={e=>pf.setValues(v=>({...v,salePrice:Number(e.target.value)}))}/></FormControl></FormItem></div><Button type="submit" disabled={busy}><Plus size={17}/>{busy?<><Spinner size="sm"/> Saving…</>:"Save product"}</Button></form></Form></article><article className={styles.listCard}><div className={styles.cardHead}><Boxes size={20}/><div><h2>Products</h2><p>{products.data?.products.length??0} active records</p></div></div>{products.isLoading?<Spinner/>:products.data?.products.length?products.data.products.map(p=><div className={styles.row} key={p.id}><div><strong>{p.name}</strong><span>{p.category||"Uncategorized"} · {p.unit}</span></div><strong>₹{p.salePrice.toLocaleString("en-IN")}</strong></div>):<div className={styles.emptyInline}>No products yet.</div>}</article></section>:
 <section className={styles.grid}><article className={styles.formCard}><div className={styles.cardHead}><Users size={20}/><div><h2>Add customer</h2><p>Mobile is optional; add it only when useful for the business.</p></div></div><Form {...cf}><form onSubmit={cf.handleSubmit(createCustomer)} className={styles.form}><FormItem name="name"><FormLabel>Customer name</FormLabel><FormControl><Input placeholder="Customer name" value={cf.values.name} onChange={e=>cf.setValues(v=>({...v,name:e.target.value}))}/></FormControl><FormMessage/></FormItem><FormItem name="mobile"><FormLabel>Mobile (optional)</FormLabel><FormControl><Input inputMode="tel" placeholder="Add if available" value={cf.values.mobile} onChange={e=>cf.setValues(v=>({...v,mobile:e.target.value}))}/></FormControl></FormItem><FormItem name="address"><FormLabel>Address (optional)</FormLabel><FormControl><Input value={cf.values.address} onChange={e=>cf.setValues(v=>({...v,address:e.target.value}))}/></FormControl></FormItem><Button type="submit" disabled={busy}><Plus size={17}/>{busy?<><Spinner size="sm"/> Saving…</>:"Save customer"}</Button></form></Form></article><article className={styles.listCard}><div className={styles.cardHead}><Users size={20}/><div><h2>Customers</h2><p>{customers.data?.customers.length??0} active records</p></div></div>{customers.isLoading?<Spinner/>:customers.data?.customers.length?customers.data.customers.map(c=><div className={styles.row} key={c.id}><div><strong>{c.name}</strong><span>{c.mobile||"No mobile added"}</span></div><strong>₹{c.openingBalance.toLocaleString("en-IN")}</strong></div>):<div className={styles.emptyInline}>No customers yet.</div>}</article></section>}
 </main>;
}