import superjson from "superjson";import { db } from "../helpers/db";import { getServerUserSession } from "../helpers/getServerUserSession";import { schema } from "./payments_POST.schema";
export async function handle(request:Request){try{const {user}=await getServerUserSession(request);const input=schema.parse(superjson.parse(await request.text()));const access=await db.selectFrom("businessMemberships").select("id").where("businessId","=",input.businessId).where("userId","=",String(user.id)).where("status","=","active").executeTakeFirst();if(!access)return new Response(superjson.stringify({message:"Business access denied"}),{status:403,headers:{"Content-Type":"application/json"}});
const result=await db.transaction().execute(async trx=>{let customerId=input.customerId||null,supplierId=input.supplierId||null,saleId=input.saleId||null,purchaseId=input.purchaseId||null;const applied=input.amount;
if(saleId){const sale=await trx.selectFrom("sales").select(["id","customerId","balanceAmount","paidAmount"]).where("id","=",saleId).where("businessId","=",input.businessId).where("status","=","confirmed").forUpdate().executeTakeFirst();if(!sale)throw new Error("Sale not found");if(input.customerId&&sale.customerId!==input.customerId)throw new Error("Payment customer does not match sale");customerId=sale.customerId;if(applied>Number(sale.balanceAmount))throw new Error("Payment exceeds sale balance");await trx.updateTable("sales").set({paidAmount:Number(sale.paidAmount)+applied,balanceAmount:Number(sale.balanceAmount)-applied,updatedAt:new Date()}).where("id","=",saleId).execute();}
if(purchaseId){const purchase=await trx.selectFrom("purchases").select(["id","supplierId","totalAmount","paidAmount"]).where("id","=",purchaseId).where("businessId","=",input.businessId).where("status","=","confirmed").forUpdate().executeTakeFirst();if(!purchase)throw new Error("Purchase not found");supplierId=purchase.supplierId;const balance=Number(purchase.totalAmount)-Number(purchase.paidAmount);if(applied>balance)throw new Error("Payment exceeds purchase balance");await trx.updateTable("purchases").set({paidAmount:Number(purchase.paidAmount)+applied,updatedAt:new Date()}).where("id","=",purchaseId).execute();}
if(!saleId&&!purchaseId&&!customerId&&!supplierId)throw new Error("A customer, supplier, sale or purchase is required");
const payment=await trx.insertInto("payments").values({businessId:input.businessId,customerId,supplierId,saleId,purchaseId,amount:applied,paymentMethod:input.paymentMethod,paymentDate:input.paymentDate?new Date(input.paymentDate):new Date(),reference:input.reference||null,notes:input.notes||null,createdBy:user.id}).returning("id").executeTakeFirstOrThrow();
if(input.scheduleId){const schedule=await trx.selectFrom("collectionSchedules").select(["id","customerId","outstandingAmount","frequency"]).where("id","=",input.scheduleId).where("businessId","=",input.businessId).where("isActive","=",true).forUpdate().executeTakeFirst();if(!schedule)throw new Error("Collection schedule not found");if(schedule.customerId!==customerId)throw new Error("Payment customer does not match collection");const outstanding=Number(schedule.outstandingAmount);if(applied>outstanding)throw new Error("Payment exceeds collection outstanding");const days={daily:1,weekly:7,fortnightly:14,monthly:30}[String(schedule.frequency)]||30;const next=new Date();next.setDate(next.getDate()+days);await trx.insertInto("collectionPayments").values({scheduleId:input.scheduleId,paymentId:payment.id,amountApplied:applied}).execute();await trx.updateTable("collectionSchedules").set({outstandingAmount:outstanding-applied,isActive:outstanding-applied>0,nextDueDate:outstanding-applied>0?next:null,updatedAt:new Date()}).where("id","=",input.scheduleId).execute();}
await trx.insertInto("auditLog").values({businessId:input.businessId,userId:user.id,action:"payment.recorded",entityType:"payment",entityId:payment.id,metadata:{amount:applied,customerId,saleId,purchaseId,scheduleId:input.scheduleId||null}}).execute();return {paymentId:payment.id,appliedAmount:applied};});
return new Response(superjson.stringify(result),{headers:{"Content-Type":"application/json"}})}catch(e){console.error("Payment error",e);return new Response(superjson.stringify({message:e instanceof Error?e.message:"Unable to record payment"}),{status:400,headers:{"Content-Type":"application/json"}})}}