import superjson from "superjson";
import { db } from "../helpers/db";
import { getServerUserSession } from "../helpers/getServerUserSession";
import { schema } from "./purchases_POST.schema";
export async function handle(request:Request){
 try{const {user}=await getServerUserSession(request);const input=schema.parse(superjson.parse(await request.text()));
 const access=await db.selectFrom("businessMemberships").select("id").where("businessId","=",input.businessId).where("userId","=",String(user.id)).where("status","=","active").executeTakeFirst();if(!access)return new Response(superjson.stringify({message:"Business access denied"}),{status:403,headers:{"Content-Type":"application/json"}});
 const location=input.locationId?await db.selectFrom("locations").select("id").where("id","=",input.locationId).where("businessId","=",input.businessId).where("isActive","=",true).executeTakeFirst():await db.selectFrom("locations").select("id").where("businessId","=",input.businessId).where("isActive","=",true).orderBy("createdAt","asc").executeTakeFirst();if(!location)throw new Error("A stock location is required");
 const result=await db.transaction().execute(async trx=>{const existing=await trx.selectFrom("purchases").select(["id","totalAmount"]).where("businessId","=",input.businessId).where("purchaseNumber","=",input.purchaseNumber).executeTakeFirst();if(existing)return {purchaseId:existing.id,totalAmount:Number(existing.totalAmount)};
 const productIds=[...new Set(input.lines.map(x=>x.productId))];const products=await trx.selectFrom("products").select("id").where("businessId","=",input.businessId).where("isActive","=",true).where("id","in",productIds).execute();if(products.length!==productIds.length)throw new Error("One or more products were not found");
 const subtotal=input.lines.reduce((s,l)=>s+l.quantity*l.unitPrice,0);if(input.discount>subtotal)throw new Error("Discount cannot exceed subtotal");const total=subtotal-input.discount;if(input.paidAmount>total)throw new Error("Paid amount cannot exceed total");
 const purchase=await trx.insertInto("purchases").values({businessId:input.businessId,supplierId:input.supplierId||null,locationId:location.id,purchaseNumber:input.purchaseNumber,purchaseDate:input.purchaseDate?new Date(input.purchaseDate):new Date(),subtotal,discount:input.discount,totalAmount:total,paidAmount:input.paidAmount,paymentMethod:input.paymentMethod||null,status:"confirmed",notes:input.notes||null,createdBy:user.id}).returning("id").executeTakeFirstOrThrow();
 for(const line of input.lines){await trx.insertInto("purchaseLines").values({purchaseId:purchase.id,productId:line.productId,quantity:line.quantity,unitPrice:line.unitPrice,lineTotal:line.quantity*line.unitPrice}).execute();await trx.insertInto("inventoryMovements").values({businessId:input.businessId,productId:line.productId,locationId:location.id,movementType:"purchase",quantity:line.quantity,unitCost:line.unitPrice,referenceType:"purchase",referenceId:purchase.id,createdBy:user.id}).execute();}
 if(input.paidAmount>0)await trx.insertInto("payments").values({businessId:input.businessId,supplierId:input.supplierId||null,purchaseId:purchase.id,amount:input.paidAmount,paymentMethod:input.paymentMethod||"cash",paymentDate:input.purchaseDate?new Date(input.purchaseDate):new Date(),notes:"Purchase payment",createdBy:user.id}).execute();
 await trx.insertInto("auditLog").values({businessId:input.businessId,userId:user.id,action:"purchase.confirmed",entityType:"purchase",entityId:purchase.id,metadata:{total,paidAmount:input.paidAmount,lines:input.lines.length}}).execute();return {purchaseId:purchase.id,totalAmount:total};});
 return new Response(superjson.stringify(result),{headers:{"Content-Type":"application/json"}})}catch(e){console.error("Purchase create error",e);return new Response(superjson.stringify({message:e instanceof Error?e.message:"Unable to create purchase"}),{status:400,headers:{"Content-Type":"application/json"}})}
}