import superjson from "superjson";
import { sql } from "kysely";
import { db } from "../helpers/db";
import { getServerUserSession } from "../helpers/getServerUserSession";
import { schema } from "./sales_POST.schema";
export async function handle(request:Request){
 try{const {user}=await getServerUserSession(request);const input=schema.parse(superjson.parse(await request.text()));const access=await db.selectFrom("businessMemberships").select("id").where("businessId","=",input.businessId).where("userId","=",String(user.id)).where("status","=","active").executeTakeFirst();if(!access)return new Response(superjson.stringify({message:"Business access denied"}),{status:403,headers:{"Content-Type":"application/json"}});
 const location=input.locationId?await db.selectFrom("locations").select("id").where("id","=",input.locationId).where("businessId","=",input.businessId).where("isActive","=",true).executeTakeFirst():await db.selectFrom("locations").select("id").where("businessId","=",input.businessId).where("isActive","=",true).orderBy("createdAt","asc").executeTakeFirst();if(!location)throw new Error("A stock location is required");
 if(input.customerId){const c=await db.selectFrom("customers").select("id").where("id","=",input.customerId).where("businessId","=",input.businessId).where("isActive","=",true).executeTakeFirst();if(!c)throw new Error("Customer not found")}
 const result=await db.transaction().execute(async trx=>{const existing=await trx.selectFrom("sales").select(["id","totalAmount","balanceAmount"]).where("businessId","=",input.businessId).where("saleNumber","=",input.saleNumber).executeTakeFirst();if(existing)return {saleId:existing.id,totalAmount:Number(existing.totalAmount),balanceAmount:Number(existing.balanceAmount)};
 const subtotal=input.lines.reduce((s,l)=>s+l.quantity*l.unitPrice,0);if(input.discount>subtotal)throw new Error("Discount cannot exceed subtotal");const total=subtotal-input.discount;if(input.paidAmount>total)throw new Error("Paid amount cannot exceed total");if(input.collection&&Math.abs(input.collection.totalAmount-total)>0.01)throw new Error("Collection total must equal sale total");if(input.collection&&!input.customerId)throw new Error("A customer is required for scheduled collections");
const unique=[...new Set(input.lines.map(x=>x.productId))];for(const productId of unique){await trx.selectFrom("products").select("id").where("id","=",productId).forUpdate().executeTakeFirstOrThrow();const stock=await trx.selectFrom("inventoryMovements").select(sql<string>`coalesce(sum(quantity),0)`.as("qty")).where("businessId","=",input.businessId).where("locationId","=",location.id).where("productId","=",productId).executeTakeFirst();const needed=input.lines.filter(x=>x.productId===productId).reduce((s,x)=>s+x.quantity,0);if(Number(stock?.qty??0)<needed)throw new Error("Insufficient stock for one or more items");}
 const balance=total-input.paidAmount;const sale=await trx.insertInto("sales").values({businessId:input.businessId,customerId:input.customerId||null,locationId:location.id,saleNumber:input.saleNumber,saleDate:input.saleDate?new Date(input.saleDate):new Date(),subtotal,discount:input.discount,totalAmount:total,paidAmount:input.paidAmount,balanceAmount:balance,paymentMethod:input.paymentMethod||null,status:"confirmed",notes:input.notes||null,createdBy:user.id}).returning("id").executeTakeFirstOrThrow();
 for(const line of input.lines){const product=await trx.selectFrom("products").select("purchasePrice").where("id","=",line.productId).executeTakeFirstOrThrow();await trx.insertInto("saleLines").values({saleId:sale.id,productId:line.productId,quantity:line.quantity,unitPrice:line.unitPrice,lineTotal:line.quantity*line.unitPrice}).execute();await trx.insertInto("inventoryMovements").values({businessId:input.businessId,productId:line.productId,locationId:location.id,movementType:"sale",quantity:-line.quantity,unitCost:Number(product.purchasePrice),referenceType:"sale",referenceId:sale.id,createdBy:user.id}).execute();}
 if(input.paidAmount>0)await trx.insertInto("payments").values({businessId:input.businessId,customerId:input.customerId||null,saleId:sale.id,amount:input.paidAmount,paymentMethod:input.paymentMethod||"cash",paymentDate:input.saleDate?new Date(input.saleDate):new Date(),notes:"Sale payment",createdBy:user.id}).execute();
 if(input.collection&&balance>0){const start=input.collection.startDate?new Date(input.collection.startDate):new Date();await trx.insertInto("collectionSchedules").values({businessId:input.businessId,customerId:input.customerId!,saleId:sale.id,title:input.collection.title,totalAmount:input.collection.totalAmount,installmentAmount:input.collection.installmentAmount,frequency:input.collection.frequency,startDate:start,nextDueDate:start,outstandingAmount:balance,isActive:true,notes:input.collection.notes||null}).execute();}
 await trx.insertInto("auditLog").values({businessId:input.businessId,userId:user.id,action:"sale.confirmed",entityType:"sale",entityId:sale.id,metadata:{total,paidAmount:input.paidAmount,balance,lines:input.lines.length}}).execute();return {saleId:sale.id,totalAmount:total,balanceAmount:balance};});
 return new Response(superjson.stringify(result),{headers:{"Content-Type":"application/json"}})}catch(e){console.error("Sale create error",e);return new Response(superjson.stringify({message:e instanceof Error?e.message:"Unable to create sale"}),{status:400,headers:{"Content-Type":"application/json"}})}
}